---

- name: Check value of variable mongodb_net_ssl_host
  ansible.builtin.fail:
    msg: 'Set mongodb_net_ssl_mode is preferSSL or set valid hostname for mongodb_net_ssl_host!'
  when: ( mongodb_net_ssl_mode == 'requireSSL'
          and mongodb_net_ssl_host|length == 0 )

- name: Check value of variable mongodb_login_host
  ansible.builtin.fail:
    msg: 'Set mongodb_login_host equal mongodb_net_ssl_host!'
  when: ( mongodb_net_ssl_mode == 'requireSSL'
          and mongodb_net_ssl_host != mongodb_login_host
          and not mongodb_replication_replset )

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

# Include the MongoDB pre-installation tasks
- name: Run pre-installation tasks
  ansible.builtin.include_tasks: preinstall.yml
  tags: [play_preinstall]

# Preconfigure YCSB for MongoDB
- name: Preconfigure YCSB for MongoDB
  ansible.builtin.include_tasks: ycsb.yml
  when: configure_ycsb
  tags: [play_ycsb]

- name: Include installation tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "install.{{ ansible_distribution | lower }}.yml"
    - "install.{{ ansible_os_family | lower }}.yml"
  tags: [mongodb]

- name: Include configuration.yml
  ansible.builtin.include_tasks: configure.yml
  tags: [mongodb]

- name: Include replication and auth configuration
  ansible.builtin.include_tasks: replication_init_auth.yml
  when: ( mongodb_replication_replset | length > 0
        and mongodb_security_authorization == 'enabled'
        and mongodb_master is defined and mongodb_master )
  tags: [mongodb]

- name: Include replication configuration
  ansible.builtin.include_tasks: replication.yml
  when: mongodb_replication_replset | length > 0
  tags: [mongodb]

- name: Check whether admin user is already exist
  ansible.builtin.command: >
    mongo --quiet {{ '--ssl --host ' + mongodb_net_ssl_host if mongodb_net_ssl_mode == 'requireSSL' else '' }} -u {{ mongodb_user_admin_name }} \
          -p {{ mongodb_user_admin_password }} --port {{ mongodb_net_port }} --eval 'db.version()' admin
  register: mongodb_user_admin_check
  changed_when: false
  check_mode: false
  ignore_errors: true
  when: ( mongodb_security_authorization == 'enabled'
          and not mongodb_replication_replset )
  no_log: true
  tags: [mongodb]

- name: Include authorization configuration
  ansible.builtin.include_tasks: auth_initialization.yml
  when: ( mongodb_security_authorization == 'enabled'
          and not mongodb_replication_replset
          and mongodb_user_admin_check.rc != 0 )
  tags: [mongodb]

- name: Create normal users with replicaset
  community.mongodb.mongodb_user:
    database: "{{ item.database }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: "{{ mongodb_user_update_password }}"
    roles: "{{ item.roles }}"
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
    login_port: "{{ mongodb_login_port | default(27017) }}"
    login_host: "{{ mongodb_login_host | default('localhost') }}"
    ssl: "{{ True if mongodb_net_ssl_mode == 'requireSSL' else False }}"
  with_items:
    - "{{ mongodb_users | default([]) }}"
  when: ( mongodb_replication_replset
        and mongodb_security_authorization == 'enabled'
        and mongodb_master is defined and mongodb_master )
  no_log: true
  tags: [mongodb]

- name: Create normal users without replicaset
  communit.mongodb.mongodb_user:
    database: "{{ item.database }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: "{{ mongodb_user_update_password }}"
    roles: "{{ item.roles }}"
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
    login_port: "{{ mongodb_net_port | int }}"
    login_host: "{{ mongodb_login_host | default('localhost') }}"
    ssl: "{{ True if mongodb_net_ssl_mode == 'requireSSL' else False }}"
  with_items:
    - "{{ mongodb_users | default([]) }}"
  when: ( mongodb_security_authorization == 'enabled'
          and not mongodb_replication_replset )
  no_log: true
  tags: [mongodb]

- name: Create oplog user with replicaset
  communit.mongodb.mongodb_user:
    database: admin
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    update_password: "{{ mongodb_user_update_password }}"
    roles:
      - db: local
        role: read
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
    login_port: "{{ mongodb_login_port | default(27017) }}"
    login_host: "{{ mongodb_login_host | default('localhost') }}"
    ssl: "{{ True if mongodb_net_ssl_mode == 'requireSSL' else False }}"
  with_items:
    - "{{ mongodb_oplog_users | default([]) }}"
  when: ( mongodb_replication_replset | length > 0
        and mongodb_security_authorization == 'enabled'
        and mongodb_master is defined and mongodb_master )
  no_log: true
  tags: [mongodb]

- name: Postinstall tasks for wiredTiger configuration
  ansible.builtin.include_tasks: postinstall.yml
  tags: [play_postinstall]

- name: Service started
  ansible.builtin.service:
    name: "{{ mongodb_daemon_name }}"
    state: started
    enabled: true

- name: Include MMS Agent configuration
  ansible.builtin.include_tasks: mms-agent.yml
  when: mongodb_mms_api_key | length > 0
  tags: [mongodb]
